# .github/workflows/generate-llms-txt.yml
name: Generate LLMS TXT files

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run npx commands to generate files
        run: |
          npx github:dotenvx/llmstxt gen https://aurorasolar.com/sitemap_index.xml \
          --replace-title 's/\| Aurora Solar$//' \
          --description "$(cat <<'EOF'
          The #1 solar software to design and sell advanced PV systems. See why installers use Aurora to create over 100,000 PV designs every week.

          ## Subindexes
          - llms-eu.txt
          - llms-helioscope.txt
          - llms-help.txt
          - llms-docs.txt

          ## Main Properties
          - [Aurora Solar Marketing Website](https://aurorasolar.com): Main marketing website showcasing product features, solutions, and resources.
          - [Aurora Solar Help Center](https://help.aurorasolar.com): Support portal with tutorials, troubleshooting, and product documentation.
          - [Aurora Solar API Documentation](https://docs.aurorasolar.com): Technical documentation for integrating with Aurora's API.
          - [Helioscope Marketing Website](https://helioscope.aurorasolar.com): Solar design and simulation software for professionals.

          ## Localized Marketing Sites
          - [Aurora EU Landing Page](https://aurorasolar.com/eu/): Central hub for Aurora's European content and region-specific offerings.
          - [Aurora Solar France](https://aurorasolar.com/eu/fr/): French-language version of the site with tailored content for France.
          - [Aurora Solar Spain](https://aurorasolar.com/eu/es/): Spanish-language version of the site with tailored content for Spain.
          - [Aurora Solar Germany](https://aurorasolar.com/eu/de/): German-language version of the site with tailored content for Germany.
          EOF
          )" > llms.txt

          npx github:dotenvx/llmstxt gen https://aurorasolar.com/eu/de/sitemap_index.xml > llms-eu.txt
          npx github:dotenvx/llmstxt gen https://help.aurorasolar.com/hc/sitemap.xml > llms-help.txt
          npx github:dotenvx/llmstxt gen https://docs.aurorasolar.com/sitemap.xml > llms-docs.txt
          npx github:dotenvx/llmstxt gen https://helioscope.aurorasolar.com/sitemap_index.xml > llms-helioscope.txt
            
      - name: Upload files to WordPress server via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          scp -i ~/.ssh/id_ed25519 -P ${{ secrets.SSH_PORT }} \
          -o StrictHostKeyChecking=yes \
            llms*.txt ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/www/aurorasolarmulti_703/public/


